### ISSUE TITLE
fail to load profile

### ISSUE THREAD

**Issue by apt42541** [VoxelCubes/PanelCleaner#10]
![image](https://user-images.githubusercontent.com/12625408/235179593-7552987c-6af1-4813-a5ec-8a89191c6c17.png)

**Comment by VoxelCubes** [comment]
It appears to be working after all! How did you do it?
That profile there is apparently corrupted.

Either `pcleaner profile repair test` to fix it or `pcleaner profile new myconf` to create a new one called myconf.

**Comment by apt42541** [comment]
problem with opencv-python , python-magic, python-magic-bin can be fixed but not data class.

**Comment by apt42541** [comment]
![image](https://user-images.githubusercontent.com/12625408/235288992-29619f63-7f89-4707-b85a-b3fec0083780.png)

**Comment by VoxelCubes** [comment]
Well, the profile is fixed now. Hopefully it isn't because of some windows shenanigans, I don't know what might be going on there. Good luck, see the prev issue about the gui and future packaging, if I can even get it working on windows.
