### ISSUE TITLE
Manual Removing, Output Preview, and Content-Aware Fill

### ISSUE THREAD

**Issue by MrFanservice-png** [VoxelCubes/PanelCleaner#103]
I know that PanelCleaner can't clean everything by itself. But I don't really see it until I get the output. That's why I suggest you add these three features:

1. A way where users can manually edit the manga images themselves using PanelCleaner so we can get any text it missed.
2. An option that allows us to view the output image before exporting it.
3. Content-aware fill so that it fills the text with surrounding areas and details (usually the white colors from speech bubbles) to remove them.

If any of these features are already available, can you tell me how to use them?

**Comment by VoxelCubes** [comment]
1. This will not happen. That is what gimp and photoshop are for. You use these anyway for typesetting, so a bit of cleaning fits right in. And those programs are far and away better at manual photo editing than Panel Cleaner can ever be, so having a shitty editor in Panel Cleaner is not worth anybody's time.

2. To do this, uncheck the "save output" checkbox on the main panel's output section, there in the top right.
Then after running, click each image and then click on the last output to see it.
I suppose this is rather unergonomic, I think I will make this a proper feature, something like "review output before saving". That's a good idea, thank you very much! It will be a few weeks before I can work on this, but it'll definitely be in a future version.

3. That's what inpainting does. If you want to select where it does this manually, well, that's again where gimp and photoshop will simply be better anyway so no need to bother.

Hope I could help. 2 and 3 are already supported, and I will improve 2 in the future.

**Comment by VoxelCubes** [comment]
2 is now fulfilled, hope you like it.
