### ISSUE TITLE
Unable to use the program (Windows)

### ISSUE THREAD

**Issue by jay-ui** [VoxelCubes/PanelCleaner#11]
It's probably just a problem that comes from me since I'm not very familiar with using codes from github. 
I downloaded pcleaner and installed it with the pip command, but when I try to use a command in the cmd prompt it says "invalid syntax", than if i try to import it or use it in python it says " ModuleNotFoundError: No module named 'pcleaner' ". If i try to install it again it says "Requirement already satisfied" a bunch of times. I'm probably missing something obvious but i don't know what it is.

**Comment by VoxelCubes** [comment]
Saying 'CMD' leads me to believe that you're on Windows, so then it's probably a path issue. You'll need to refer to windows help resources on how to address that, I'm not really sure what the problem is, haven't used in on windows. I just know that it's a pain to set python up correctly there.

Regardless, if 'pcleaner -v' says it can't find it, try 'python -m pcleaner.main -v', or if it can't find it, check if 'python --version' even works. Good luck!

PS. when I'm done with the gui in a month or two, I'll try to make a windows exe such that you don't need to install python in the first place.

**Comment by jay-ui** [comment]
Thanks for the answer. Yeah i'm on windows, so it's most likely the problem here.
I do have python installed but 'pcleaner -v' returns "invalid syntax" and 'python -m pcleaner.main -v' returns "Error while finding module specification for 'pcleaner.main' (ModuleNotFoundError: No module named 'pcleaner')". I'll try to set up a path for it and see if it works after that.

**Comment by Arwagollon** [comment]
when i trye python -m pcleaner.main -v it gives me error: 
![obrazek](https://github.com/VoxelCubes/PanelCleaner/assets/76229377/f90f37ea-41f0-4938-815c-88be5ec974ea)

**Comment by Arwagollon** [comment]
> Thanks for the answer. Yeah i'm on windows, so it's most likely the problem here. I do have python installed but 'pcleaner -v' returns "invalid syntax" and 'python -m pcleaner.main -v' returns "Error while finding module specification for 'pcleaner.main' (ModuleNotFoundError: No module named 'pcleaner')". I'll try to set up a path for it and see if it works after that.

I solved it winh adding python in user variables --> https://projects.raspberrypi.org/en/projects/using-pip-on-windows/4  and then turn of aliasis https://stackoverflow.com/questions/24186823/python-not-recognized-in-windows-cmd-even-after-adding-to-path  

![obrazek](https://github.com/VoxelCubes/PanelCleaner/assets/76229377/45a2ea71-8df8-4efd-bcd6-0eb6513200ea)
![obrazek](https://github.com/VoxelCubes/PanelCleaner/assets/76229377/359f0cb7-c9de-47ee-97e0-de2534d34bab)
 You have to add python folder and python scripts folder with \ in the and of the path! And Edit environment variables just for your account and try to net delete all system variables for path like me :D.

**Comment by VoxelCubes** [comment]
That's great! I'll leave this one open so that people looking for help are more likely to see it.
Also, I am able to run it on windows, but my efforts to build an exe so far have been in vain.

**Comment by VoxelCubes** [comment]
Please try the Windows pre-built binary that is now available as the 2.0 release, if problems persist.
