### ISSUE TITLE
 Optimize for manhwa (webtoons)  large dimensions

### ISSUE THREAD

**Issue by wolfkingal2000** [VoxelCubes/PanelCleaner#122]
Hi, when I use this for manhwa (webtoons) with large dimensions, like 800x10000, I want to implement a tiling mode to process the image in smaller sections, such as splitting it into 5 tiles of 800x2000 each. This should optimize the processing specifically for manhwa by improving the quality, speeding up the process, and ensuring the text detection is accurate for each tile. and give back 800x10000 to me

**Comment by VoxelCubes** [comment]
As I suppose you've realized by the fact that you've closed the issue yourself, this is out of the scope for Panel Cleaner. Write a tiny script to do that for you instead.
