### ISSUE TITLE
Optimize for manhwa (webtoons) large dimensions

### ISSUE THREAD

**Issue by wolfkingal2000** [VoxelCubes/PanelCleaner#123]
Hi, when I use this for manhwa (webtoons) with large dimensions, like 800x10000, I want to implement a tiling mode to process the image in smaller sections, such as splitting it into 5 tiles of 800x2000 each. This should optimize the processing specifically for manhwa by improving the quality, speeding up the process, and ensuring the text detection is accurate for each tile. and give back 800x10000 to me

**Comment by VoxelCubes** [comment]
Ok maybe I'll look into it. I have an idea that could improve the split location, so it isn't just at a fixed place, but automatically chooses one without much going on. As long as it doesn't prove to be too complicated to integrate...

**Comment by VoxelCubes** [comment]
Fixed in Release 2.11
