### ISSUE TITLE
add new detector  model

### ISSUE THREAD

**Issue by wolfkingal2000** [VoxelCubes/PanelCleaner#125]
i think this model can helpful

https://huggingface.co/ogkalu/comic-text-segmenter-yolov8m
https://huggingface.co/ogkalu/comic-speech-bubble-detector-yolov8m
https://huggingface.co/ogkalu/manga-text-detector-yolov8s

**Comment by VoxelCubes** [comment]
Thanks for the links, nice to see some alternative approaches. 
Here though, without any documentation or code surrounding them, I don't have the time nor interest to tinker to maybe get them working, and huggingface labeling one of the files as malicious (likely a false positive, but who knows) doesn't help the matter.

Thanks for looking though!
