### ISSUE TITLE
Add manual inpainting 

### ISSUE THREAD

**Issue by wolfkingal2000** [VoxelCubes/PanelCleaner#129]
Add manual inpainting for area model can't be detecting

**Comment by VoxelCubes** [comment]
Anything manual when it comes to cleaning should be done in a competent image editor, this is an absolute line I won't cross with this project.
A proper image editor will do this way better than any half-baked image editor I could construct.

**Comment by wolfkingal2000** [comment]
I don't mean clean like image editor software  i telling some area dont detect  on detector can add or add more better detector

**Comment by VoxelCubes** [comment]
You'll want to ask the guys who make comic text detector about that, I don't make the detector. https://github.com/dmMaze/comic-text-detector
