### ISSUE TITLE
Problems running on Windows

### ISSUE THREAD

**Issue by KaapaTeelb** [VoxelCubes/PanelCleaner#13]
Can't use program on average, something just broken along the way
Installed via PyPi, added extra with pip install -r requirements.txt from original github repo, but.... idk just doesent work???

GUI:
![image](https://github.com/VoxelCubes/PanelCleaner/assets/8286113/129c2c79-59b9-49b6-b362-02098c251db7)

Normal usecase (?):
![image](https://github.com/VoxelCubes/PanelCleaner/assets/8286113/14fa6f41-8ee3-4f84-bc1d-6a546c7f9bea)

Magic ver(cuz ig its important or smth):
![image](https://github.com/VoxelCubes/PanelCleaner/assets/8286113/4e371f4b-c104-4e1e-8931-82e96db27998)

**Comment by KaapaTeelb** [comment]
Also used 
![image](https://github.com/VoxelCubes/PanelCleaner/assets/8286113/d20de5b2-55bd-4216-955d-72ec1cdc3264) 
fix

**Comment by Arwagollon** [comment]
How did you make the program start on win? i get thise errors. It is probabli mistake on my side, even if it looks like it is broken i woud like to knew what i do wrong. When I try "python -m pcleaner.main -v" it gives me an error: 
![obrazek](https://github.com/VoxelCubes/PanelCleaner/assets/76229377/f90f37ea-41f0-4938-815c-88be5ec974ea)
![obrazek](https://github.com/VoxelCubes/PanelCleaner/assets/76229377/8362489c-44e0-451e-bf28-f0bb0f20beaa)

**Comment by VoxelCubes** [comment]
Frankly, I haven't been able to get it to work on windows either, I probably gotta delete and make a new virtual machine at this point.
If and when I do get it working, I'll provide an .exe for all of you having issues. Till then, I don't know how to make it work either :(

You can, of course, always just use WSL (Haven't used that myself either, but heard it works).

**Comment by justme7678876788** [comment]
> Can't use program on average, something just broken along the way Installed via PyPi, added extra with pip install -r requirements.txt from original github repo, but.... idk just doesent work???
> 
> GUI: ![image](https://user-images.githubusercontent.com/8286113/240794370-129c2c79-59b9-49b6-b362-02098c251db7.png)
> 
> Normal usecase (?): ![image](https://user-images.githubusercontent.com/8286113/240794628-14fa6f41-8ee3-4f84-bc1d-6a546c7f9bea.png)
> 
> Magic ver(cuz ig its important or smth): ![image](https://user-images.githubusercontent.com/8286113/240795509-4e371f4b-c104-4e1e-8931-82e96db27998.png)

Hi . i solved this problem by just installing `pip install python-magic-bin` and not python-magic but i still got to another problem

**Comment by VoxelCubes** [comment]
Please try the Windows pre-built binary that is now available as the 2.0 release.
