### ISSUE TITLE
mac os metal

### ISSUE THREAD

**Issue by imKota** [VoxelCubes/PanelCleaner#15]
Can yo add support metal?
https://developer.apple.com/metal/pytorch/

**Comment by VoxelCubes** [comment]
I don't own any Apple hardware, so I am not able to develop this. If anyone knows what he's doing and is able to test an implementation, I'd be happy to merge it though.

**Comment by VoxelCubes** [comment]
I'm very happy to let you know that this has been done in #85 by civvic. It'll be in the next release.

**Comment by VoxelCubes** [comment]
Release 2.7.0 is now live, hope it works for you (though I think support is just for newer macs).

**Comment by imKota** [comment]
@VoxelCubes Still the same processing works only by the processor.

I have another suggestion, how about making it possible to use a remote docker container with cuda support?

For example:
I have a server with a video card, I run the PanelCleaner docker container on it, inside it is running with the parameters panelclener --server 3000 --p pass -u user

I run PanelCleaner on any operating system, in the handler settings (local/remote) I choose remote server, address as ip:port, login and password.

What do you think about this?

**Comment by VoxelCubes** [comment]
I honestly have no clue regarding that kind of stuff. If it works for you, that's great. Someone else contributed a docker file, have you tried it and it didn't work or am I missing something?

**Comment by imKota** [comment]
> I honestly have no clue regarding that kind of stuff. If it works for you, that's great. Someone else contributed a docker file, have you tried it and it didn't work or am I missing something?

I meant to run PanelCleaner from macos, but have the processing happen on a remote server.

**Comment by VoxelCubes** [comment]
Yeah that works regardless over ssh and the CLI. Not what this issue here was about.
