### ISSUE TITLE
BallonTranslator x PanelCleaner

### ISSUE THREAD

**Issue by bropines** [VoxelCubes/PanelCleaner#17]
You can also combine your project and the program from the author of comix-text-detector, in his program. Here is the link. You may be interested https://github.com/dmMaze/BallonsTranslator

**Comment by VoxelCubes** [comment]
That's indeed a neat project, I'm aware of it. Thanks for sharing!

The ballons tool is more of an integrated editor, by the looks of it, whereas I'm aiming to have fun making an automatic cleaning step, that should just do as much as it can automatically before a human has to work on the output, using whatever far more advanced, conventional image editor he chooses. 

Not sure how you envision combining them, it seems like they already are using the same comic text detector engine for cleaning and probably have some of their own cleanup routines to make it usable.

**Comment by bropines** [comment]
I wrote, maybe your project works better. And your repository was also liked by the creator of ballons translator).

**Comment by VoxelCubes** [comment]
Oh wow, I didn't see that he had done that, that's nice to know :)
Thanks!
