### ISSUE TITLE
Add CSV OCR Output

### ISSUE THREAD

**Issue by UserJHansen** [VoxelCubes/PanelCleaner#18]
Hi, 

I think it would be useful to get a csv file out of the ocr mode for identifying where the text is and to make it easier to work with.

I will work on implementing this and there should be a pull request soon, the csv output should follow this pattern:

| filename | startx | starty | endx | endy | text |
|----|----|----|----|----|----|

**Comment by VoxelCubes** [comment]
Oh, yes that's a good idea, it'd make it easier to pipe that into other programs. It'd be best to add it as another flag like --csv for the ocr mode. If you have any questions or issues, I'll gladly help.

**Comment by VoxelCubes** [comment]
Oh, I just gave it a look and you already thought of implementing it as a --csv option, excellent. I'll review the PR shortly, thanks!
