### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by eberamp** [VoxelCubes/PanelCleaner#2]
Want to contribute by adding Docker support, can I get permissions to push?

The advantage to run the app in a container is that you install only the dependencies required by said application and also avoid conflicting dependencies and versions of Python (for those that require a specific python installation)

**Comment by VoxelCubes** [comment]
I do not know how to make one, so if you could do that, it would be fantastic! Gladly!
I tried to make a Flatpak to cover that same concern, but couldn't get it to work.

**Comment by VoxelCubes** [comment]
If by "permission to push" you mean being a collaborator, that isn't necessary. You just need to fork the repository and then open a pull request after committing fixes for a new feature. Then I can simply review your suggested changes and merge them, easy.

If you cloned the repo and made changes there, just fork the repo, clone that locally, copy your modified files over, commit that, and then you can open your pull request. That way, you don't need my permission to do it.

**Comment by eberamp** [comment]
Huh I hadn't done it that way sorry for the ignorance, I already opened the PR https://github.com/VoxelCubes/PanelCleaner/pull/3, the usage should still be the same just inside a container, I have tested in macOS no CUDA support and works well, I just had some issues using custom profiles not sure if it's a dependency issue will look into it later

**Comment by eberamp** [comment]
By the way I wanted to contribute and improve on the model/code and expand on other ideas but not sure how to get started if you've got a few pointers in regards to ML/AI to get started that'd be great

**Comment by VoxelCubes** [comment]
Ah, awesome, thank you very much. I'll look into that as well.

As for improving pcleaner, the accuracy really depends on the ML model, indeed. I didn't write the model, nor did I train it. You can find links to the projects in the readme's acknowledgements. In particular, pcleaner relies on Comic Text Detector to generate the masks, which aren't perfect and sometimes mess up. All pcleaner does is improves the quality of the masks to make them usable for cleaning, but if the initial mask has grave defects, well, it's *garbage in, garbage out.* 

I don't know much about AI, so best I can do is direct you towards the project: [Comic Text Detector](https://github.com/dmMaze/comic-text-detector)
If you do train a new model, you can load it explicitly by giving a new path inside a profile. It's the `model_path` variable.

Other than AI, you could try optimizing the profile's settings for a given series, using the copious analytics to see if it improved the process. For that, I recommend disabling the steps that aren't affected by your changes, like the text detection and preprocessing, with the -T and -P flags, respectively. This will make iterating on your changes quicker.

**Comment by eberamp** [comment]
No problems, I'll take a look at that, we could also improve on what you already have, I've tried to use other tools but honestly they just don't work as much lol

**Comment by VoxelCubes** [comment]
Sure, if you have any further topics you would like to discuss, a separate issue, or the discussion section, may be more appropriate. Have fun tinkering :)
