### ISSUE TITLE
Additional text added outside of text inside of images. 

### ISSUE THREAD

**Issue by EagleEye17** [VoxelCubes/PanelCleaner#24]
Panel Cleaner's OCR has an issue with adding text that is nonexistent to the original image file.

It seems to add them at the tail end of the sentence sequence.

This is what Panel Cleaner's output straight from the text file:

**_102-2.png:_** 
まとめてーぶっ飛ばせー！
こんななんでもありバトルロイヤルビーチフラッグだとは聞いてませんよ！？
あはは！だから面白いんじゃない♪
ちなみに賞品はなんです？
なんと～！指揮官とのデート券！！
そうなんですか！チーム戦だから３枚？
残念～！１枚！お宝は早い者勝ちだかんね！
そんな殺生な！？
優勝チーム内で更にバトルです．．．？
ありがとうございました。はいはい。ですが、そのためにこの時期があります。

This should be the expected output:

102-2.png: 
まとめてーぶっ飛ばせー！
こんななんでもありバトルロイヤルビーチフラッグだとは聞いてませんよ！？
あはは！だから面白いんじゃない♪
ちなみに賞品はなんです？
なんと～！指揮官とのデート券！！
そうなんですか！チーム戦だから３枚？
残念～！１枚！お宝は早い者勝ちだかんね！
そんな殺生な！？
優勝チーム内で更にバトルです．．．？

That last sentence string shouldn't even be there. I verified the text count using the isolated text function. It shows nine text boxes but has a tenth sentence added to it.

**Comment by VoxelCubes** [comment]
Thanks for the extra details you sent over email, I've now fixed the issue in release [2.1.0 ](https://github.com/VoxelCubes/PanelCleaner/releases/tag/2.1.0)

The problem boiled down to the OCR model trying to OCR English text, which it isn't trained on, resulting in gibberish. That now gets ignored properly, with configurable strictness.

Thanks for bringing this to my attention!
