### ISSUE TITLE
is it possible to export the text as a txt file? (yes im really lazy)

### ISSUE THREAD

**Issue by EfeDevirgen** [VoxelCubes/PanelCleaner#42]

**Comment by VoxelCubes** [comment]
Literally the default option for OCR. The alternative is csv. If that isn't what you meant, then put more effort into your question, please.

**Comment by EfeDevirgen** [comment]
ok i googled what ocr is thx sry for askin a dumb question:P

**Comment by VoxelCubes** [comment]
Ah, that makes sense. It happens, no problem.
