### ISSUE TITLE
MagicException: cannot read magic file

### ISSUE THREAD

**Issue by GH6** [VoxelCubes/PanelCleaner#87]
**Describe the bug**

**To Reproduce**
I dropped in the folder, selected only the mask option, and pressed start. It looks like all the files are processed, then I get an error.

**Expected behavior**

**Session Log**

2024-05-01 00:01:07.162 | INFO     | pcleaner.gui.launcher:launch:65 - 
- Program Information -
Program: Panel Cleaner 2.6.1
Executing from: C:\\PanelCleaner-Windows-unzip_me\_internal\pcleaner\gui\launcher.pyc
Log file: C:\Users\<username>\AppData\Roaming\pcleaner\cache\pcleaner.log
Config file: C:\Users\<username>\AppData\Roaming\pcleaner\pcleanerconfig.ini
Cache directory: C:\Users\<username>\AppData\Roaming\pcleaner\cache
- System Information -
Operating System: Windows 10
Machine: AMD64
Python Version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
PySide (Qt) Version: 6.6.2
Available Qt Themes: windowsvista, Windows, Fusion
System locale: ko_KR
CPU Cores: 8
GPU: None (CUDA not available)

2024-05-01 00:25:44.663 | INFO     | pcleaner.gui.processing:generate_output:225 - Running preprocessing for 56 images...
2024-05-01 00:25:44.664 | WARNING  | pcleaner.gui.image_tab:update_tabs:122 - Updating tabs with step 1.
2024-05-01 00:25:44.664 | DEBUG    | pcleaner.preprocessor:prep_json_file:68 - Processing json file: C:\Users\<username>\AppData\Roaming\pcleaner\cache\cleaner\633064b1-b138-443b-8192-8cbec3f73b32_@new_05_Chieri_san2_02_001#raw.json
2024-05-01 00:25:44.667 | CRITICAL | pcleaner.gui.mainwindow_driver:output_worker_error:1421 - Encountered an error while processing files.
Traceback (most recent call last):

> File "pcleaner\gui\worker_thread.py", line 141, in run

  File "pcleaner\gui\mainwindow_driver.py", line 1303, in generate_output

  File "pcleaner\gui\processing.py", line 241, in generate_output

  File "pcleaner\preprocessor.py", line 115, in prep_json_file

  File "pcleaner\structures.py", line 246, in grow_boxes

  File "pcleaner\structures.py", line 208, in image_size

  File "magic\magic.py", line 134, in from_file

  File "magic\magic.py", line 122, in _get_magic_type

  File "magic\magic.py", line 71, in __init__

  File "magic\magic.py", line 272, in magic_load

  File "magic\magic.py", line 203, in errorcheck_negative_one

magic.magic.MagicException: b"cannot read magic file `C:\\\xec\x9e\x91\xec\x97\x85\\PanelCleaner-Windows-unzip_me\\_internal\\magic\\libmagic\\magic.mgc' (Illegal byte sequence)"
2024-05-01 00:33:09.449 | DEBUG    | pcleaner.gui.mainwindow_driver:open_issue_reporter:728 - Opening issue reporter.

**Screenshots**

**Additional context**

+Only partial logs were entered due to character limitations.

**Comment by VoxelCubes** [comment]
Thanks for the test files, I'll take a look over the weekend.

**Comment by GH6** [comment]
I wondered if the problem is that the directory where PanelCleaner.exe is located has Korean folder names, so I changed them to English. When I did, I got a lot of Failed results. Why is this?

OCR Analytics
━━━━━━━━━━━━━
Number of boxes: 8 | Number of small boxes: 0 (0%)
Number of removed boxes: 0 (0% total, N/A of small boxes)
No not-removed small boxes found.
        
Mask Fitment Analytics
━━━━━━━━━━━━━━━━━━━━━━
Total boxes: 7 | Masks succeeded: 4 (57%) | Masks failed: 3
Perfect masks: 2 (50%) | Average border deviation: 4.47

Mask usage by thickness (in pixels):
Mask (4px) : █████████████████████████ 0 / 2
Mask (6px) :  0 / 0
Mask (8px) :  0 / 0
Mask (10px):  0 / 0
Mask (12px):  0 / 0
Mask (14px):  0 / 0
Mask (16px): ████████████ 1 / 1
Mask (18px):  0 / 0
Mask (20px): ████████████ 1 / 1
Mask (22px):  0 / 0
Mask (24px):  0 / 0
Box mask   :  0 / 0
Failed     : ██████████████████████████████████████ 3

█ Perfect | █ Total | █ Failed 


Pages with failures / total:
04_Chieri_san3_1_003.jpg: 3 / 7
        
Denoising Analytics
━━━━━━━━━━━━━━━━━━━
Total masks: 7 | Masks denoised: 5 (71%)
Minimum deviation to denoise: 0.25 | Maximum allowed deviation: 15
Standard deviation around masks:

 0.00- 0.01 : ███████████████████████████████████ 0 / 2
 0.01- 0.12 :  0 / 0
 0.12- 0.40 :  0 / 0
 0.40- 0.96 :  0 / 0
 0.96- 1.88 :  0 / 0
 1.88- 3.24 :  0 / 0
 3.24- 5.14 :  0 / 0
 5.14- 7.68 : █████████████████ 1 / 1
 7.68-10.93 : █████████████████ 1 / 1
10.93-15.00 :  0 / 0

█ Denoised | █ Total
        
OCR Analytics
━━━━━━━━━━━━━
Number of boxes: 678 | Number of small boxes: 6 (1%)
Number of removed boxes: 3 (0% total, 50% of small boxes)

Small box sizes:
   0- 500:  0 / 0
 500-1000:  0 / 0
1000-1500:  0 / 0
1500-2000: ████████████████████ 0 / 2
2000-2500: ████████████████████ 1 / 2
2500-3000: ████████████████████ 2 / 2

█ Small boxes | █ Removed boxes

Removed bubbles:
Page 34_Chieri_san3_1_033.jpg: ．．．！
Page 37_Chieri_san3_1_036.jpg: ．．．．．．
Page 38_Chieri_san3_1_037.jpg: ！！
        
Mask Fitment Analytics
━━━━━━━━━━━━━━━━━━━━━━
Total boxes: 674 | Masks succeeded: 513 (76%) | Masks failed: 161
Perfect masks: 458 (89%) | Average border deviation: 0.58

Mask usage by thickness (in pixels):
Mask (4px) : ██████████ 0 / 45
Mask (6px) : ███▏ 14 / 18
Mask (8px) : ████▏ 19 / 22
Mask (10px): ████████▏ 36 / 37
Mask (12px): ██████████▏ 44 / 46
Mask (14px): ██████████████ 60 / 60
Mask (16px): ██████████ 43 / 43
Mask (18px): ████████ 37 / 37
Mask (20px): ██████ 29 / 29
Mask (22px): ████ 17 / 17
Mask (24px): ███████ 32 / 32
Box mask   : █████████████████████████████ 127 / 127
Failed     : ██████████████████████████████████████ 161

█ Perfect | █ Total | █ Failed 


Pages with failures / total:
04_Chieri_san3_1_003.jpg: 3 / 7
06_Chieri_san3_1_005.jpg: 3 / 20
07_Chieri_san3_1_006.jpg: 5 / 13
08_Chieri_san3_1_007.jpg: 1 / 5
09_Chieri_san3_1_008.jpg: 1 / 21
10_Chieri_san3_1_009.jpg: 10 / 19
11_Chieri_san3_1_010.jpg: 6 / 16
12_Chieri_san3_1_011.jpg: 4 / 11
13_Chieri_san3_1_012.jpg: 6 / 6
14_Chieri_san3_1_013.jpg: 2 / 10
15_Chieri_san3_1_014.jpg: 3 / 11
16_Chieri_san3_1_015.jpg: 3 / 10
17_Chieri_san3_1_016.jpg: 1 / 13
18_Chieri_san3_1_017.jpg: 4 / 12
19_Chieri_san3_1_018.jpg: 7 / 12
20_Chieri_san3_1_019.jpg: 1 / 9
21_Chieri_san3_1_020.jpg: 4 / 9
23_Chieri_san3_1_022.jpg: 3 / 5
24_Chieri_san3_1_023.jpg: 6 / 13
25_Chieri_san3_1_024.jpg: 7 / 16
26_Chieri_san3_1_025.jpg: 2 / 9
27_Chieri_san3_1_026.jpg: 1 / 1
28_Chieri_san3_1_027.jpg: 3 / 7
29_Chieri_san3_1_028.jpg: 2 / 4
30_Chieri_san3_1_029.jpg: 1 / 7
32_Chieri_san3_1_031.jpg: 1 / 10
35_Chieri_san3_1_034.jpg: 4 / 21
37_Chieri_san3_1_036.jpg: 1 / 10
38_Chieri_san3_1_037.jpg: 1 / 9
41_Chieri_san3_1_040.jpg: 1 / 10
43_Chieri_san3_1_042.jpg: 3 / 5
45_Chieri_san3_1_044.jpg: 1 / 14
46_Chieri_san3_1_045.jpg: 1 / 10
47_Chieri_san3_1_046.jpg: 8 / 14
51_Chieri_san3_1_050.jpg: 4 / 14
52_Chieri_san3_1_051.jpg: 7 / 11
53_Chieri_san3_1_052.jpg: 6 / 18
54_Chieri_san3_1_053.jpg: 3 / 13
56_Chieri_san3_1_055.jpg: 1 / 11
57_Chieri_san3_1_056.jpg: 4 / 4
58_Chieri_san3_1_057.jpg: 5 / 8
59_Chieri_san3_1_058.jpg: 7 / 13
60_Chieri_san3_1_059.jpg: 6 / 10
61_Chieri_san3_1_060.jpg: 4 / 9
62_Chieri_san3_1_061.jpg: 1 / 3
64_Chieri_san3_1_063.jpg: 1 / 14
65_Chieri_san3_1_064.jpg: 2 / 11
        
Denoising Analytics
━━━━━━━━━━━━━━━━━━━
Total masks: 674 | Masks denoised: 196 (29%)
Minimum deviation to denoise: 0.25 | Maximum allowed deviation: 15
Standard deviation around masks:

 0.00- 0.01 : ███████████████████████████████████ 0 / 458
 0.01- 0.12 : ▏ 0 / 10
 0.12- 0.40 : ▏ 1 / 11
 0.40- 0.96 : ▏ 1 / 1
 0.96- 1.88 : ▏ 2 / 2
 1.88- 3.24 : ▏ 2 / 2
 3.24- 5.14 : ▏ 3 / 3
 5.14- 7.68 : ▏ 4 / 4
 7.68-10.93 : ▏ 9 / 9
10.93-15.00 : ▏ 13 / 13

█ Denoised | █ Total

**Comment by GH6** [comment]
I wondered if the problem was that the directory where PanelCleaner is located has a Korean folder name, so I changed it to English. After doing so, the image conversion succeeded, but I got a lot of failed results. Why is this happening?

        
OCR Analytics
━━━━━━━━━━━━━
Number of boxes: 8 | Number of small boxes: 0 (0%)
Number of removed boxes: 0 (0% total, N/A of small boxes)
No not-removed small boxes found.
        
Mask Fitment Analytics
━━━━━━━━━━━━━━━━━━━━━━
Total boxes: 7 | Masks succeeded: 4 (57%) | Masks failed: 3
Perfect masks: 2 (50%) | Average border deviation: 4.47

Mask usage by thickness (in pixels):
Mask (4px) : █████████████████████████ 0 / 2
Mask (6px) :  0 / 0
Mask (8px) :  0 / 0
Mask (10px):  0 / 0
Mask (12px):  0 / 0
Mask (14px):  0 / 0
Mask (16px): ████████████ 1 / 1
Mask (18px):  0 / 0
Mask (20px): ████████████ 1 / 1
Mask (22px):  0 / 0
Mask (24px):  0 / 0
Box mask   :  0 / 0
Failed     : ██████████████████████████████████████ 3

█ Perfect | █ Total | █ Failed 


Pages with failures / total:
04_Chieri_san3_1_003.jpg: 3 / 7
        
Denoising Analytics
━━━━━━━━━━━━━━━━━━━
Total masks: 7 | Masks denoised: 5 (71%)
Minimum deviation to denoise: 0.25 | Maximum allowed deviation: 15
Standard deviation around masks:

 0.00- 0.01 : ███████████████████████████████████ 0 / 2
 0.01- 0.12 :  0 / 0
 0.12- 0.40 :  0 / 0
 0.40- 0.96 :  0 / 0
 0.96- 1.88 :  0 / 0
 1.88- 3.24 :  0 / 0
 3.24- 5.14 :  0 / 0
 5.14- 7.68 : █████████████████ 1 / 1
 7.68-10.93 : █████████████████ 1 / 1
10.93-15.00 :  0 / 0

█ Denoised | █ Total
        
OCR Analytics
━━━━━━━━━━━━━
Number of boxes: 678 | Number of small boxes: 6 (1%)
Number of removed boxes: 3 (0% total, 50% of small boxes)

Small box sizes:
   0- 500:  0 / 0
 500-1000:  0 / 0
1000-1500:  0 / 0
1500-2000: ████████████████████ 0 / 2
2000-2500: ████████████████████ 1 / 2
2500-3000: ████████████████████ 2 / 2

█ Small boxes | █ Removed boxes

Removed bubbles:
Page 34_Chieri_san3_1_033.jpg: ．．．！
Page 37_Chieri_san3_1_036.jpg: ．．．．．．
Page 38_Chieri_san3_1_037.jpg: ！！
        
Mask Fitment Analytics
━━━━━━━━━━━━━━━━━━━━━━
Total boxes: 674 | Masks succeeded: 513 (76%) | Masks failed: 161
Perfect masks: 458 (89%) | Average border deviation: 0.58

Mask usage by thickness (in pixels):
Mask (4px) : ██████████ 0 / 45
Mask (6px) : ███▏ 14 / 18
Mask (8px) : ████▏ 19 / 22
Mask (10px): ████████▏ 36 / 37
Mask (12px): ██████████▏ 44 / 46
Mask (14px): ██████████████ 60 / 60
Mask (16px): ██████████ 43 / 43
Mask (18px): ████████ 37 / 37
Mask (20px): ██████ 29 / 29
Mask (22px): ████ 17 / 17
Mask (24px): ███████ 32 / 32
Box mask   : █████████████████████████████ 127 / 127
Failed     : ██████████████████████████████████████ 161

█ Perfect | █ Total | █ Failed 


Pages with failures / total:
04_Chieri_san3_1_003.jpg: 3 / 7
06_Chieri_san3_1_005.jpg: 3 / 20
07_Chieri_san3_1_006.jpg: 5 / 13
08_Chieri_san3_1_007.jpg: 1 / 5
09_Chieri_san3_1_008.jpg: 1 / 21
10_Chieri_san3_1_009.jpg: 10 / 19
11_Chieri_san3_1_010.jpg: 6 / 16
12_Chieri_san3_1_011.jpg: 4 / 11
13_Chieri_san3_1_012.jpg: 6 / 6
14_Chieri_san3_1_013.jpg: 2 / 10
15_Chieri_san3_1_014.jpg: 3 / 11
16_Chieri_san3_1_015.jpg: 3 / 10
17_Chieri_san3_1_016.jpg: 1 / 13
18_Chieri_san3_1_017.jpg: 4 / 12
19_Chieri_san3_1_018.jpg: 7 / 12
20_Chieri_san3_1_019.jpg: 1 / 9
21_Chieri_san3_1_020.jpg: 4 / 9
23_Chieri_san3_1_022.jpg: 3 / 5
24_Chieri_san3_1_023.jpg: 6 / 13
25_Chieri_san3_1_024.jpg: 7 / 16
26_Chieri_san3_1_025.jpg: 2 / 9
27_Chieri_san3_1_026.jpg: 1 / 1
28_Chieri_san3_1_027.jpg: 3 / 7
29_Chieri_san3_1_028.jpg: 2 / 4
30_Chieri_san3_1_029.jpg: 1 / 7
32_Chieri_san3_1_031.jpg: 1 / 10
35_Chieri_san3_1_034.jpg: 4 / 21
37_Chieri_san3_1_036.jpg: 1 / 10
38_Chieri_san3_1_037.jpg: 1 / 9
41_Chieri_san3_1_040.jpg: 1 / 10
43_Chieri_san3_1_042.jpg: 3 / 5
45_Chieri_san3_1_044.jpg: 1 / 14
46_Chieri_san3_1_045.jpg: 1 / 10
47_Chieri_san3_1_046.jpg: 8 / 14
51_Chieri_san3_1_050.jpg: 4 / 14
52_Chieri_san3_1_051.jpg: 7 / 11
53_Chieri_san3_1_052.jpg: 6 / 18
54_Chieri_san3_1_053.jpg: 3 / 13
56_Chieri_san3_1_055.jpg: 1 / 11
57_Chieri_san3_1_056.jpg: 4 / 4
58_Chieri_san3_1_057.jpg: 5 / 8
59_Chieri_san3_1_058.jpg: 7 / 13
60_Chieri_san3_1_059.jpg: 6 / 10
61_Chieri_san3_1_060.jpg: 4 / 9
62_Chieri_san3_1_061.jpg: 1 / 3
64_Chieri_san3_1_063.jpg: 1 / 14
65_Chieri_san3_1_064.jpg: 2 / 11
        
Denoising Analytics
━━━━━━━━━━━━━━━━━━━
Total masks: 674 | Masks denoised: 196 (29%)
Minimum deviation to denoise: 0.25 | Maximum allowed deviation: 15
Standard deviation around masks:

 0.00- 0.01 : ███████████████████████████████████ 0 / 458
 0.01- 0.12 : ▏ 0 / 10
 0.12- 0.40 : ▏ 1 / 11
 0.40- 0.96 : ▏ 1 / 1
 0.96- 1.88 : ▏ 2 / 2
 1.88- 3.24 : ▏ 2 / 2
 3.24- 5.14 : ▏ 3 / 3
 5.14- 7.68 : ▏ 4 / 4
 7.68-10.93 : ▏ 9 / 9
10.93-15.00 : ▏ 13 / 13

█ Denoised | █ Total

**Comment by GH6** [comment]
One of the directories had a Korean name. I changed it to an English name and it worked.

**Comment by GH6** [comment]
I'll refer back to the guide to set up the profile, as I didn't understand the program well enough.
And I have one more question.
If I use this program to translate manga and make my work public, do I need to put the program logo or a link to GitHub in the work image?

**Comment by VoxelCubes** [comment]
To enable inpainting in the gui, you go to the inpainting section of the profile settings and check "enable inpainting", then press apply. You can also save the profile to make that more convenient. 

You do not need to attribute this project for stuff you used it for. The only license here is in regards to using the source code, the GPLv3 license.

Feel free to let other people know you used it, if you want more people to know about it, but you don't have to do any of that.

I'm not sure I can actually fix your issue, since this problem occurs in the program code of imagemagic, rather than panel cleaner. We'll see.
