### ISSUE TITLE
 Failed to load icon mask_denoised.svg for dark/light theme

### ISSUE THREAD

**Issue by GH6** [VoxelCubes/PanelCleaner#89]
**Describe the bug**
C:\Users\sging>pcleaner gui
qt.svg: Cannot open file ':/custom_icons/dark/mask_denoised.svg', because: Input/output error
qt.svg: Cannot open file ':/custom_icons/dark/mask_denoised.svg', because: Input/output error
2024-05-02 01:14:36.004 | ERROR    | pcleaner.gui.file_table:__init__:105 - Failed to load icon mask_denoised.svg for dark theme.
qt.svg: Cannot open file ':/custom_icons/light/mask_denoised.svg', because: Input/output error
qt.svg: Cannot open file ':/custom_icons/light/mask_denoised.svg', because: Input/output error
2024-05-02 01:14:36.008 | ERROR    | pcleaner.gui.file_table:__init__:105 - Failed to load icon mask_denoised.svg for light theme.
2024-05-02 01:14:36.013 | WARNING  | pcleaner.gui.image_tab:update_tabs:122 - Updating tabs with step None.

**To Reproduce**
1.  run terminal and excecute pcleaner gui
2. see error above

**Expected behavior**

**Session Log**
If the program's gui starts, click on the "Show Log" button in the bottom right to view the current
or past logs. Click the "Copy to Clipboard" button and paste entire log of the session with the issue
here. That will include all relevant system information for you as well.

**Screenshots**

**Additional context**
I ran it in the terminal to use CUDA, but then it got stuck with an error, how do I fix it?

**Comment by VoxelCubes** [comment]
This is related to the same technical issue as #88
