### ISSUE TITLE
[FR] Bulgarian Language Support bg_BG

### ISSUE THREAD

**Issue by librafrog** [VoxelCubes/PanelCleaner#93]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to create the translation by editing the `.ts file`. I've forked the project. That's all for know. If I understand correctly if i've built the project from source I can live-check the translation ✔️  

**Describe alternatives you've considered**
—

**Additional context**
When ready, I'm gonna try to make a pull request to you branch

**Comment by VoxelCubes** [comment]
That's awesome! Be sure to generate a new .ts file using the makefile though, so that it's metadata is correct. No copy pasting and renaming one of the existing ones. If you haven't already, I can do thatbreal quick. I didn't document that step properly.

**Comment by librafrog** [comment]
yes, if you don't mind generate one.

**Comment by librafrog** [comment]
all works well, except before actually running refresh assets how to start with the bare bone .ts file.

**Comment by VoxelCubes** [comment]
What does DW mean?
Hm, that's very odd. Oh, I think I know what's wrong.
The script uses some relative file paths to find the PySide utility programs to do the actual conversion processes, like lupdate.exe, but if you didn't install the dependencies into a directory called venv inside the project directory, you'll need to update them in the script, so it knows where to find them.
So either update the paths to the utility programs with wherever they are on your system, or set up a vitual environment called venv in the project root.
